# Generated by Django 3.2.8 on 2021-11-01 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybetmodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mybetmodel',
            name='race_on_time',
            field=models.DateTimeField(),
        ),
    ]
